"""Update short_url

Revision ID: 4190277ebc8f
Revises: f9a7c1302494
Create Date: 2026-01-03 16:20:24.665992

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4190277ebc8f"
down_revision: Union[str, Sequence[str], None] = "f9a7c1302494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "links",
        "short_url",
        existing_type=sa.VARCHAR(length=36),
        type_=sqlmodel.sql.sqltypes.AutoString(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "links",
        "short_url",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
        type_=sa.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
